name: grg
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - ca-certificates=2021.4.13
  - certifi=2020.12.5
  - ld_impl_linux-64=2.33.1
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1k
  - pip=21.1.1
  - python=3.9.5
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.35.4
  - tk=8.6.10
  - tzdata=2020f
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
